config/routes.rb
ISSAD::Application.routes.draw do

  root to: 'main#home', via: :get
  
  match 'faq', to: 'main#faq', via: :get, as: :faq
  
  # for mobile
   match 'newtopic', to: 'main#newtopic', via: :get, as: :newtopic
  # end for mobile 
   
  
  match '/search/topics', to: 'main#searchtopics', via: :get, as: :searchtopics
  match '/search/maps', to: 'main#searchmaps', via: :get, as: :searchmaps
  match '/search/mappers', to: 'main#searchmappers', via: :get, as: :searchmappers
  match '/search/synapses', to: 'main#searchsynapses', via: :get, as: :searchsynapses
  
  match 'maps/:id/savelayout', to: 'maps#savelayout', via: :put, as: :savelayout
  match 'topics/:map_id/:topic_id/removefrommap', to: 'topics#removefrommap', via: :post, as: :removefrommap
  match 'synapses/:map_id/:synapse_id/removefrommap', to: 'synapses#removefrommap', via: :post, as: :removefrommap
  
  resources :topics, except: [:index, :new, :edit] do
    get :autocomplete_topic, :on => :collection
  end
  match 'topics/:id/:format', to: 'topics#json', via: :get, as: :json
  
  resources :synapses, except: [:index, :new, :edit, :show]
  match 'synapses/:id/:format', to: 'synapses#json', via: :get, as: :json
  
  match 'maps/active', to: 'maps#index', via: :get, as: :activemaps
  match 'maps/new', to: 'maps#index', via: :get, as: :newmaps
  match 'maps/mappers/:id', to: 'maps#index', via: :get, as: :usermaps
  match 'maps/topics/:id', to: 'maps#index', via: :get, as: :topicmaps
  
  
  resources :maps, except: [:new, :edit]
  match 'maps/:id/embed', to: 'maps#embed', via: :get, as: :embed
  match 'maps/:id/:format', to: 'maps#json', via: :get, as: :json
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  
  resources :users, except: :show

  resources :mappings
  
end

app/models/map.rb
class Map < ActiveRecord::Base

belongs_to :user

has_many :topicmappings, :class_name => 'Mapping', :conditions => {:category => 'Topic'}
has_many :synapsemappings, :class_name => 'Mapping', :conditions => {:category => 'Synapse'}

has_many :topics, :through => :topicmappings
has_many :synapses, :through => :synapsemappings

def mappings 
	topicmappings + synapsemappings
end

def mk_permission
  if self.permission == "commons"
    "co"
  elsif self.permission == "public"
    "pu"
  elsif self.permission == "private"
    "pr"
  end
end

  #return an array of the contributors to the map
  def contributors
    contributors = []
    
    self.mappings.each do |m|
      contributors.push(m.user) if !contributors.include?(m.user)
    end
    
    return contributors
  end
  
  
  ###### JSON ######
  #build a json object of a map
  def self_as_json(current)
    Jbuilder.encode do |json|
	  @topics = self.topics
	  @synapses = self.synapses
	  
	  json.array!(@topics.delete_if{|topic| not topic.authorize_to_view(current)}) do |topic|
		
		#json.adjacencies topic.synapses2.delete_if{|synapse| (not @topics.include?(synapse.topic1)) || (not @synapses.include?(synapse)) || (not synapse.authorize_to_view(current)) || (not synapse.topic1.authorize_to_view(current)) } do |json, synapse|
		
	      json.adjacencies topic.synapses1.delete_if{|synapse| (not @synapses.include?(synapse)) || (not @topics.include?(synapse.topic2)) || (not synapse.authorize_to_view(current)) || (not synapse.topic2.authorize_to_view(current)) } do |json, synapse|
				json.nodeTo synapse.node2_id
				json.nodeFrom synapse.node1_id
				
				@synapsedata = Hash.new
				@synapsedata['$desc'] = synapse.desc
				@synapsedata['$showDesc'] = false
				@synapsedata['$category'] = synapse.category
				@synapsedata['$id'] = synapse.id
				@synapsedata['$userid'] = synapse.user.id
				@synapsedata['$username'] = synapse.user.name
				@synapsedata['$direction'] = [synapse.node1_id.to_s(), synapse.node2_id.to_s()]
        @synapsedata['$permission'] = synapse.permission
				json.data @synapsedata
		  end
		  
		  @inmaps = Array.new
      @mapsString = ""
      topic.maps.each_with_index do |map, index|
        @inmaps.push(map.id)
        @mapsString += map.name
        @mapsString += (index+1) == topic.maps.count ? "" : ", "
      end
      
		  @topicdata = Hash.new
		  @topicdata['$desc'] = topic.desc
		  @topicdata['$link'] = topic.link
		  @topicdata['$metacode'] = topic.metacode.name
      @topicdata['$inmaps'] = @inmaps
      @topicdata['$inmapsString'] = @mapsString
      @topicdata['$synapseCount'] = topic.synapses.count
		  @topicdata['$userid'] = topic.user.id
		  @topicdata['$username'] = topic.user.name
		  @mapping = Mapping.find_by_topic_id_and_map_id(topic.id,self.id)
		  @topicdata['$xloc'] = @mapping.xloc
		  @topicdata['$yloc'] = @mapping.yloc
		  @topicdata['$mappingid'] = @mapping.id
      @topicdata['$permission'] = topic.permission
      @topicdata['$date'] = topic.created_at.strftime("%m/%d/%Y")
		  json.data @topicdata
		  json.id topic.id
		  json.name topic.name
	  end	
    end
  end
  
  ##### PERMISSIONS ######
  
  scope :visibleToUser, lambda { |current, user|  
    if user != nil
	   if user != current
		 Map.find_all_by_user_id_and_permission(user.id, "commons") | Map.find_all_by_user_id_and_permission(user.id, "public")
	   elsif user ==  current
	     Map.find_all_by_user_id_and_permission(user.id, "commons") | Map.find_all_by_user_id_and_permission(user.id, "public") | current.maps.where(:permission => "private")
	   end
	elsif (current != nil && user == nil) 
		Map.find_all_by_permission("commons") | Map.find_all_by_permission("public") | current.maps.where(:permission => "private")
	elsif (current == nil) 
		Map.find_all_by_permission("commons") | Map.find_all_by_permission("public")
	end
  }
  
  # returns false if user not allowed to 'show' Topic, Synapse, or Map
  def authorize_to_show(user)  
	if (self.permission == "private" && self.user != user)
		return false
	end
	return self
  end
  
  # returns false if user not allowed to 'edit' Topic, Synapse, or Map
  def authorize_to_edit(user)  
	if (self.permission == "private" && self.user != user)
		return false
	elsif (self.permission == "public" && self.user != user)
		return false
	end
	return self
  end
  
  # returns Boolean if user allowed to view Topic, Synapse, or Map
  def authorize_to_view(user)  
	if (self.permission == "private" && self.user != user)
		return false
	end
	return true
  end
  
  # returns Boolean based on whether user has permissions to edit or not
  def authorize_linkto_edit(user)
    if (self.user == user)
		return true
    elsif (self.permission == "commons")
		return true
	end
	return false
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  
  before_filter :require_user, only: [:new, :create, :edit, :update, :savelayout, :destroy]
    
  respond_to :html, :js, :json
  
  autocomplete :map, :name, :full => true, :extra_data => [:user_id]
  
  # GET /maps/recent
  # GET /maps/new
  # GET /maps/mappers/:id
  def index
    
    if request.path == "/maps"
      redirect_to activemaps_url and return
    end
    
    @current = current_user
    @user = nil
    
    if request.path =="/maps/active"
      @maps = Map.order("updated_at DESC").limit(20)
      @request = "active"
      
    elsif request.path == "/maps/new"
      @maps = Map.order("created_at DESC").limit(20)
      @request = "new"
      
    elsif request.path.index('/maps/mappers/') != nil  # looking for maps by a mapper
      @user = User.find(params[:id])
      @maps = Map.order("name ASC").find_all_by_user_id(@user.id)
      @request = "you" if authenticated? && @user == @current
      @request = "other" if authenticated? && @user != @current
      
    elsif request.path.index('/maps/topics/') != nil  # looking for maps by a certain topic they include
      @topic = Topic.find(params[:id]).authorize_to_show(@current)
      if !@topic
        redirect_to featuredmaps_url, notice: "Access denied." and return
      end
      @maps = @topic.maps
      @request = "topic"
    end
    
    #read this next line as 'delete a map if its private and you're either 1. logged out or 2. logged in but not the map creator
    @maps.delete_if {|m| m.permission == "private" && (!authenticated? || (authenticated? && @current.id != m.user_id)) }
    
	  respond_with(@maps, @request, @user)
  end
  
  # GET maps/new
  def new
  	@map = Map.new
    @user = current_user
    
    respond_with(@map)
  end
  
  # GET maps/:id
  def show
  	
	  @current = current_user
	  @map = Map.find(params[:id]).authorize_to_show(@current)
	
	  if not @map
	    redirect_to root_url and return
	  end
		
	  @mapjson = @map.self_as_json(@current).html_safe
	
	  respond_to do |format|
      format.html { respond_with(@map, @user) }
      format.json { respond_with(@mapjson) }
    end
  end
  
  # GET maps/:id/embed
  def embed
  	
	  @current = current_user
	  @map = Map.find(params[:id]).authorize_to_show(@current)
	
	  if not @map
	    redirect_to root_url and return
	  end
		
	  @mapjson = @map.self_as_json(@current).html_safe
	
	  respond_to do |format|
      format.html { respond_with(@map, @user) }
      format.json { respond_with(@mapjson) }
    end
  end
  
  # GET maps/:id/json
  def json
  	
	  @current = current_user
	  @map = Map.find(params[:id]).authorize_to_show(@current)
	
	  if not @map
	    redirect_to root_url and return
	  end
		
	  respond_to do |format|
      format.json { render :json => @map.self_as_json(@current) }
    end
  end
  
  # POST maps
  def create
    
    @user = current_user
    @map = Map.new()
    @map.name = params[:map][:name]
    @map.desc = params[:map][:desc]
    @map.permission = params[:map][:permission]
    @map.user = @user
    @map.arranged = false    
    @map.save   

    #this variable specifies to the js file whether it's a brand new map or a forked one
    @forked = false    
	  
    if params[:map][:topicsToMap]
      @all = params[:map][:topicsToMap]
      @all = @all.split(',')
      @all.each do |topic|
        topic = topic.split('/')
        @mapping = Mapping.new()
        @mapping.category = "Topic"
        @mapping.user = @user
        @mapping.map  = @map
        @mapping.topic = Topic.find(topic[0])
        @mapping.xloc = topic[1]
        @mapping.yloc = topic[2]
        @mapping.save
      end

      if params[:map][:synapsesToMap]
        @synAll = params[:map][:synapsesToMap]
        @synAll = @synAll.split(',')
        @synAll.each do |synapse_id|
          @mapping = Mapping.new()
          @mapping.category = "Synapse"
          @mapping.user = @user
          @mapping.map = @map
          @mapping.synapse = Synapse.find(synapse_id)
          @mapping.save
        end
      end

      @map.arranged = true
      @map.save
      
      @forked = true
    end
    
    respond_to do |format|
      format.js { respond_with(@map, @forked) }
    end
  end
  
  # GET maps/:id/edit
  def edit
	  @current = current_user
	  @map = Map.find(params[:id]).authorize_to_edit(@current)
	
	  if not @map
	    redirect_to root_url and return
	  end
	
	  @outtopics = @map.topics.order("name ASC").delete_if{|topic| not topic.authorize_to_view(@current)}
  
	  respond_with(@user, @map, @outtopics)
  end
  
  # PUT maps/:id
  def update
	  @current = current_user
	  @map = Map.find(params[:id]).authorize_to_edit(@current)
    
	  if @map 
        if params[:map]
          @map.name = params[:map][:name] if params[:map][:name]
		      @map.desc = params[:map][:desc] if params[:map][:desc]
		      @map.permission = params[:map][:permission] if params[:map][:permission]
        end
	    @map.save
    end

    respond_with @map
  end
  
  # PUT maps/:id/savelayout
  def savelayout
    @user = current_user
    @map = Map.find(params[:id])
  
    if params[:map][:coordinates]
      @all = params[:map][:coordinates]
      @all = @all.split(',')
      @all.each do |topic|
        topic = topic.split('/')
        @mapping = Mapping.find(topic[0])
        if @mapping
          @mapping.xloc = topic[1]
          @mapping.yloc = topic[2]
          @mapping.save
          
          #push realtime update for location on map
          @mapping.message 'update',@user.id
        end
      end
      @map.arranged = true
      @map.touch(:updated_at)
      @map.save
    end	
  end
  
  # DELETE maps/:id
  def destroy
    @current = current_user
  
	  @map = Map.find(params[:id])
	
	  @mappings = @map.mappings
	
	  @mappings.each do |mapping| 
		  mapping.delete
	  end
	
	  @map.delete
	
	  respond_to do |format|
        format.html { redirect_to "/maps/mappers/" + @current.id.to_s, notice: "Map deleted." }
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper

  ## this one is for building our custom JSON autocomplete format for typeahead
  def autocomplete_map_array_json(maps)
    temp = []
    maps.each do |m|
      map = {}
      map['id'] = m.id
      map['label'] = m.name
      map['value'] = m.name
      map['description'] = m.desc.truncate(30)
      map['permission'] = m.permission
      map['topicCount'] = m.topics.count
      map['synapseCount'] = m.synapses.count
      map['contributorCount'] = m.contributors.count
      map['rtype'] = "map"
      
      contributorList = m.user.name + ' created this map. '
      if m.contributors.count > 0 
          m.contributors.each_with_index do |c, index|
            comma = (index+1) == m.contributors.count ? '' : ', '
            contributorList += c.name + comma
          end
          contributorList += ' has edited it.' if m.contributors.count == 1
          contributorList += ' have edited it.' if m.contributors.count > 1
      else
        contributorList += 'No one has added anything yet.'      
      end
      map['contributorList'] = contributorList
      
      temp.push map
    end
    return temp
  end

end

app/views/maps/_fork.html.erb
<%#
  # @file
  # Partial view, renders a form that creates a new map.
  #%>
<div class="onConsole">
<%= form_for Map.new, url: maps_url, remote: true, html: { class: "new_map", id: "fork_map" } do |form|%>
  
  <% if controller_name == "maps" %>
    <h3 class="forCreateMap">Save To New Map</h3>
  <% elsif controller_name == "topics" %>
    <h3 class="forCreateMap">Save As New Map</h3>
  <% end %>
  
  <div class="inputGroup">
    <label for="map_name">Name: </label>
    <%= form.text_field :name %>
    <div class="clearfloat"></div>
  </div>
  
  <div class="inputGroup">
    <label for="map_desc">Description: </label>
    <%= form.text_area :desc, class: "description", :rows => 5, :cols => 43 %>
    <div class="clearfloat"></div>
  </div>
  
  <div class="inputGroup">
    <label for="map_permission">Permission: </label>    
    
    <div class="permIcon" data-permission="commons">
      <div class="mapCommonsIcon mapPermIcon selected hoverForTip">
        <div class="tip">
          Collaborate with other mappers on editing this map. Those without accounts can view this map.
        </div>
      </div>
      <h4>COMMONS</h4>
    </div>
    <div class="permIcon" data-permission="public">
      <div class="mapPublicIcon mapPermIcon hoverForTip">
        <div class="tip">
          Anyone, with or without an account, can view this map but not edit anything.
        </div>
      </div>
      <h4>PUBLIC</h4>
    </div>
    <div class="permIcon" data-permission="private">
      <div class="mapPrivateIcon mapPermIcon hoverForTip">
        <div class="tip">
          Only you can view or edit this map.
        </div>
      </div>
      <h4>PRIVATE</h4>
    </div>
    
    <%= form.hidden_field :permission, :value => "commons" %>
    <div class="clearfloat"></div>
  </div>
  
  <p class="permText">*new topics and synapses take on the same permission as the map they are created on</p>
  
  <div class="buttonWrapper">
    <button class="button" onclick="cancelMapCreate('fork_map'); return false;">Cancel</button>
    <%= form.submit "Create!", class: "add" %>
  </div>
  
  <%= form.hidden_field :topicsToMap, :value => 0 %>
  <%= form.hidden_field :synapsesToMap, :value => 0 %>
  <div class="clearfloat"></div>
<% end %>
</div>

app/views/maps/_homemap.html.erb
<%#
  # @file
  # Shows a map as a card.
  # Any list of maps uses this rendering.
  #%>
<figure class="map <%= first ? "current" : "" %>">
  <a href="/maps/<%= map.id %>">
  <div class="permission <%= map.authorize_to_edit(user) ? "canEdit" : "cannotEdit" %>">  
  
	  <div class="mapCard"> 
      <div class="mapPerm <%= map.mk_permission %>"></div>    
      <span class="title">                                                  
        <%= best_in_place map, :name, :type => :input, :classes => 'best_in_place_name' %>                             
      </span> 
      <div class="mapContains">      
        <span class="topicCount"><%= pluralize(map.topics.count, 'topic') %></span>                 
        <span class="synapseCount"><%= pluralize(map.synapses.count, 'synapse') %></span>
      </div>
      <div class="littleOverlay">      
        <div class="scroll">                                                    
          <div class="desc">                                                    
            <%= best_in_place map, :desc, :type => :textarea, :nil => "<span class='gray'>Click to add description.</span>", :classes => 'best_in_place_desc' %>                          
          </div>                                                                
        </div>
        <span><%= pluralize(map.contributors.count, 'contributor') %></span><span>Last edit <%= time_ago_in_words( map.updated_at ) %> ago</span>
      </div>      
    </div>
  
  </div>
  </a>
</figure>

app/views/maps/_map.html.erb
<%#
  # @file
  # Shows a map as a card.
  # Any list of maps uses this rendering.
  #%>
<%= div_for map do %>
  <div class="permission <%= map.authorize_to_edit(user) ? "canEdit" : "cannotEdit" %>">  
  
	  <div class="mapCard">                                                   
      <span class="title">                                                  
        <%= best_in_place map, :name, :type => :input, :classes => 'best_in_place_name' %>                             
      </span>                                                              
      <div class="links">                                                   
         <div class="linkItem icon">                                             
            <div class="metacodeImage" style="background-image:url(/assets/map.png);"></div>                 
         </div>                                                             
         <div class="linkItem contributor hoverForTip">
           <div class="tip">Created by <%= map.user.name %> on <%= map.created_at.strftime("%m/%d/%Y") %></div>
         </div>                           
         <div class="linkItem topicCount"><%= map.topics.count %></div>                 
         <div class="linkItem synapseCount"><%= map.synapses.count %></div>         
         <div class="linkItem mapPerm <%= map.mk_permission %>"></div>             
         <a href="/maps/<%= map.id %>" class="linkItem topicPopout" title="Open Map in New Tab" target="_blank"></a>
         <div class="clearfloat"></div>                                     
      </div>                                                                
      <div class="scroll">                                                    
        <div class="desc">                                                    
          <%= best_in_place map, :desc, :type => :textarea, :nil => "<span class='gray'>Click to add description.</span>", :classes => 'best_in_place_desc' %>                          
          <div class="clearfloat"></div>                                
        </div>                                                                
      </div>                                                                  
      <div class="clearfloat"></div>                                          
    </div>
  
  </div>
<% end %>

app/views/maps/_new.html.erb
<%#
  # @file
  # Partial view, renders a form that creates a new map.
  #%>
<div class="onConsole">
<%= form_for Map.new, url: maps_url, remote: true, html: { class: "new_map", id: "new_map" } do |form|%>
  <h3 class="forCreateMap">Create A New Map</h3>
  
  <div class="inputGroup">
    <label for="map_name">Name: </label>
    <%= form.text_field :name %>
    <div class="clearfloat"></div>
  </div>
  
  <div class="inputGroup">
    <label for="map_desc">Description: </label>
    <%= form.text_area :desc, class: "description", :rows => 5, :cols => 43 %>
    <div class="clearfloat"></div>
  </div>
  
  <div class="inputGroup">
    <label for="map_permission">Permission: </label>    
    
    <div class="permIcon" data-permission="commons">
      <div class="mapCommonsIcon mapPermIcon selected hoverForTip">
        <div class="tip">
          Collaborate with other mappers on editing this map. Those without accounts can view this map.
        </div>
      </div>
      <h4>COMMONS</h4>
    </div>
    <div class="permIcon" data-permission="public">
      <div class="mapPublicIcon mapPermIcon hoverForTip">
        <div class="tip">
          Anyone, with or without an account, can view this map but not edit anything.
        </div>
      </div>
      <h4>PUBLIC</h4>
    </div>
    <div class="permIcon" data-permission="private">
      <div class="mapPrivateIcon mapPermIcon hoverForTip">
        <div class="tip">
          Only you can view or edit this map.
        </div>
      </div>
      <h4>PRIVATE</h4>
    </div>
    
    <%= form.hidden_field :permission, :value => "commons" %>
    <div class="clearfloat"></div>
  </div>
  
  <p class="permText">*new topics and synapses take on the same permission as the map they are created on</p>
  
  <div class="buttonWrapper">
    <button class="button" onclick="cancelMapCreate('new_map'); return false;">Cancel</button>
    <%= form.submit "Create!", class: "add" %>
  </div>
  
  <div class="clearfloat"></div>
<% end %>
</div>

app/views/maps/_newtopic.html.erb
<%#
  # Partial rendering form for a new topic on a map
  # This code is called when viewing a metamap in show.html.erb in the views/maps folder
  #%>
<div class="anypage">
<%= form_for Topic.new, url: topics_url, remote: true do |form| %>
  <div id="metacodeImg">
    <% @m = user.settings.metacodes %>
    <% @metacodes = [] %>
    <% @m.each do |m| %>
      <% @metacodes.push(Metacode.find(m.to_i)) %>
    <% end %>
    <% @metacodes.sort! {|m1,m2| m2.name.downcase <=> m1.name.downcase }.rotate!(-1) %>
    <% @metacodes.each do |metacode| %>
      <img class="cloudcarousel" width="40" height="40" src="/assets/<%= metacode.icon %>" alt="<%= metacode.name %>" title="<%= metacode.name %>"/>
    <% end %>
  </div> 
  <%= form.text_field :name, :maxlength => 140, :placeholder => "title..." %>
  <%= form.hidden_field :metacode, :value => "Action" %>
  <%= form.hidden_field :x, :value => 0 %>
  <%= form.hidden_field :y, :value => 0 %>
  <% if (@map.permission == "commons" && authenticated?) || @map.user == user %>
    <%= form.hidden_field :map, :value => @map.id %>
  <% end %>
  <%= form.hidden_field :grabTopic, :value => "null" %>
  <%= form.hidden_field :addSynapse, :value => false %>
  <div id="metacodeImgTitle"></div>
  <div class="clearfloat"></div>
<% end %>
</div>

app/views/maps/create.js.erb
/*
 * @file
 * Javascript run on creation of a new map
 */

 
$('#map_name').val('');
$('#map_desc').val('');
$('#map_permission').val('commons');

<% if @forked %>
  $('#map_topicsToMap').val('0');
  $('#map_synapsesToMap').val('0');
  
  var form = $('#fork_map');
<% else %>
  var form = $('#new_map');
<% end %>
form.find('.mapPermIcon').removeClass('selected');
form.find('.mapCommonsIcon').addClass('selected');


var tempForm = form.html();
if (mapid == null) {
  form.html("Success! Do you want to <br> <a href='/maps/" + '<%= @map.id %>' + "'>Go to your new map?</a><br>or<br><a href='#' onclick='closeIt(); return false;'>Stay on this page?</a>");
}
else if (mapid != null) {
  form.html("Success! Do you want to <br> <a href='/maps/" + '<%= @map.id %>' + "'>Go to your new map?</a><br>or<br><a href='#' onclick='closeIt(); return false;'>Stay on this map?</a>");
}
$('#lightbox_main').css('margin-top', '-' + ($('#lightbox_main').height() / 2) + 'px' );

function closeIt() {
  $('#lightbox_overlay').hide();
  form.html(tempForm);
  // bind permission changer events
  form.find('.permIcon').click(function() {
    $(this).siblings('#map_permission').val( $(this).attr('data-permission') );
    $(this).siblings('.permIcon').find('.mapPermIcon').removeClass('selected');
    $(this).find('.mapPermIcon').addClass('selected');
  });
}

app/views/maps/destroy.js.erb
/*
 * @file
 * Javascript run on destruction of a map. Fades it out from map index.
 */
$('#<%= dom_id(@map) %>').fadeOut('slow');

app/views/maps/embed.html.erb
<%#
  # @file
  # Code to display a map
  # /maps/:id
  #%>

<% content_for :title, @map.name + " | Metamaps" %>   
  
<div class="headertop">
    <% if authenticated? %>
      <% if (@map.permission == "commons" && authenticated?) || @map.user == user %>
        <button onclick="removeSelectedEdges();removeSelectedNodes();">Remove Selected From Map</button>
      <% end %>
      <button onclick="var r=confirm('Are you sure you want to permanently delete selected objects?!'); if (r == true) {deleteSelectedEdges();deleteSelectedNodes();}">Permanently Delete Selected</button>
      <% if (@map.permission == "commons" && authenticated?) || @map.user == user %>
			  <%= form_for @map, :url => savelayout_path(@map), :html => { :class => "saveMapLayout", :id => "saveMapLayout"}, remote: true do |form| %>
				  <%= form.hidden_field "coordinates", :value => "" %>
				  <%= form.submit "Save Layout", class: "saveLayout", id: "saveLayout" %>
			  <% end %>
		  <% end %>
    <% end %>
</div>
<div class="clearfloat"></div>

<div class="maps onMap white_bg" id="container">
  <div id="center-container">
    <div id="infovis"></div>    
  </div>
</div>
<div class="clearfloat"></div>

<% if authenticated? %>
  <%= render :partial => 'newtopic' %>
  <%= render :partial => 'newsynapse' %>
<% end %>
  
<script>
  var dragged = 0;
  mapid = <%= @map.id %>;
  <% if (@map.permission == "commons" && authenticated?) || @map.user == user %>
    mapperm = true;
  <% end %>
</script>

<script>
  viewMode = "graph";
	json = <%= @mapjson %>;
	if (json.length > 0) {
		$(document).ready(function() {
			<% if (@map.arranged) %>
				initialize("arranged", false, true);
			<% else %>
				initialize("chaotic", false, true);
			<% end %>
		});
	}
  else {
		$(document).ready(function() {
				initialize("chaotic", true, true);
		});
	}
  MetamapsModel.embed = true;
</script>

app/views/maps/index.mobile.erb
<% content_for :title, "My Maps" %>
 

  <% if @maps.length > 0 %>  
  <ul data-role="listview" data-inset="true" data-filter="true">
    <% @maps.each do |m| %>
      <li><a href="/maps/<%= m.id %>"><img class="ui-li-icon" src="/assets/map.png" width="30" /><%= m.name %></a></li>
    <% end %>
  </ul>
  <% else %>
  There are no metamaps yet.
  <% end %>

app/views/maps/savelayout.js.erb
/*
 * @file
 * Javascript executed when you save the layout of a map.
 */
$('.sidebarSave .tip').html('Saved!');
setTimeout(function(){ $('.sidebarSave .tip').html('Save Layout') },1500);