config/routes.rb
ISSAD::Application.routes.draw do

  root to: 'main#home', via: :get
  
  match 'faq', to: 'main#faq', via: :get, as: :faq
  
  # for mobile
   match 'newtopic', to: 'main#newtopic', via: :get, as: :newtopic
  # end for mobile 
   
  
  match '/search/topics', to: 'main#searchtopics', via: :get, as: :searchtopics
  match '/search/maps', to: 'main#searchmaps', via: :get, as: :searchmaps
  match '/search/mappers', to: 'main#searchmappers', via: :get, as: :searchmappers
  match '/search/synapses', to: 'main#searchsynapses', via: :get, as: :searchsynapses
  
  match 'maps/:id/savelayout', to: 'maps#savelayout', via: :put, as: :savelayout
  match 'topics/:map_id/:topic_id/removefrommap', to: 'topics#removefrommap', via: :post, as: :removefrommap
  match 'synapses/:map_id/:synapse_id/removefrommap', to: 'synapses#removefrommap', via: :post, as: :removefrommap
  
  resources :topics, except: [:index, :new, :edit] do
    get :autocomplete_topic, :on => :collection
  end
  match 'topics/:id/:format', to: 'topics#json', via: :get, as: :json
  
  resources :synapses, except: [:index, :new, :edit, :show]
  match 'synapses/:id/:format', to: 'synapses#json', via: :get, as: :json
  
  match 'maps/active', to: 'maps#index', via: :get, as: :activemaps
  match 'maps/new', to: 'maps#index', via: :get, as: :newmaps
  match 'maps/mappers/:id', to: 'maps#index', via: :get, as: :usermaps
  match 'maps/topics/:id', to: 'maps#index', via: :get, as: :topicmaps
  
  
  resources :maps, except: [:new, :edit]
  match 'maps/:id/embed', to: 'maps#embed', via: :get, as: :embed
  match 'maps/:id/:format', to: 'maps#json', via: :get, as: :json
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  
  resources :users, except: :show

  resources :mappings
  
end

app/controllers/synapses_controller.rb
class SynapsesController < ApplicationController
  include TopicsHelper

  before_filter :require_user, only: [:create, :update, :removefrommap, :destroy]
    
  respond_to :html, :js, :json
  
  # GET synapses/:id/json
  def json
    @current = current_user
    @synapse = Synapse.find(params[:id]).authorize_to_show(@current)
	
    if not @synapse
	    redirect_to root_url and return
    end
	
    respond_to do |format|
      format.json { render :json => @synapse.selfplusnodes_as_json }
    end
  end
  
  # POST synapses
  def create
    @user = current_user
    
    # if the topic exists grab it and return it
    if params[:synapse][:grabSynapse] != "null"
        @synapse = Synapse.find(params[:synapse][:grabSynapse])
    # if not selecting an existing synapse, create it
    else
      @synapse = Synapse.new()
      @synapse.desc = params[:synapse][:desc]
      @synapse.topic1 = Topic.find(params[:synapse][:topic1id])
      @synapse.topic2 = Topic.find(params[:synapse][:topic2id])
      @synapse.permission = "commons"
      @synapse.category = "from-to"
      @synapse.weight = 5
      @synapse.user = @user	
      @synapse.save  
    end     
	
    if params[:synapse][:map]
      @map = Map.find(params[:synapse][:map])
      @map.touch(:updated_at)
      
      @mapping = Mapping.new()
      @mapping.category = "Synapse"
      @mapping.user = @user
      @mapping.map = @map
      @mapping.synapse = @synapse
      @mapping.save
      
      #push add to map to realtime viewers of the map
      @mapping.message 'create',@user.id
      
      # set the permission of the synapse to whatever the permission of the 
      #map is
      @synapse.permission = @map.permission
      @synapse.save
	  end
    
    respond_to do |format|
      format.html { respond_with(@user, location: synapse_url(@synapse)) }
      format.js { respond_with(@synapse) }
    end
    
  end
  
  # PUT synapses/:id
  def update
	  @current = current_user
    @synapse = Synapse.find(params[:id]).authorize_to_edit(@current)
    
	  if @synapse
      @permissionBefore = @synapse.permission
      
      if params[:synapse]
        @synapse.desc = params[:synapse][:desc] if params[:synapse][:desc]
	      @synapse.category = params[:synapse][:category] if params[:synapse][:category]
	      @synapse.permission = params[:synapse][:permission] if params[:synapse][:permission]
      end
      if params[:node1_id] and params[:node1_id][:node1]
	      @synapse.topic1 = Topic.find(params[:node1_id][:node1])
      end
      if params[:node2_id] and params[:node2_id][:node2]
	      @synapse.topic2 = Topic.find(params[:node2_id][:node2])
      end
	    @synapse.save
      
      @permissionAfter = @synapse.permission
      
      #push notify to anyone viewing this synapse on a map in realtime (see mapping.rb to understand the 'message' action)
      # if the topic was private and is being switched to PU or CO it is the same as being created for other viewers
      if @permissionBefore == "private" and @permissionAfter != "private"
        @synapse.message 'create',@current.id
      elsif @permissionBefore != "private" and @permissionAfter == "private"
        @synapse.message 'destroy',@current.id
      else 
        @synapse.message 'update',@current.id
      end
    end
	
    respond_to do |format|
      format.js
      format.json { respond_with(@synapse) }
    end
  end

  # POST synapses/:map_id/:synapse_id/removefrommap
  def removefrommap
    @user = current_user
   
    @mapping = Mapping.find_by_synapse_id_and_map_id(params[:synapse_id],params[:map_id])
    
    Map.find(params[:map_id]).touch(:updated_at)
    
    #push notify to anyone viewing same map in realtime (see mapping.rb to understand the 'message' action)
    @mapping.message 'destroy',@user.id
    
    @mapping.delete

    respond_to do |format|
      format.js
    end
  end
  
  # DELETE synapses/:id
  def destroy
    @current = current_user
    @synapse = Synapse.find(params[:id]).authorize_to_edit(@current)

    @synapse.mappings.each do |m|
    
      m.map.touch(:updated_at)
      
      #push notify to anyone viewing same map in realtime (see mapping.rb to understand the 'message' action)
      m.message 'destroy',@current.id
    
      m.delete
    end

    @synapse.delete if @synapse
  end
end

app/helpers/synapses_helper.rb
module SynapsesHelper

  
  ## this one is for building our custom JSON autocomplete format for typeahead
  def autocomplete_synapse_generic_json(unique)
    temp = []
    unique.each do |s|
      synapse = {}
      synapse['label'] = s.desc
      synapse['value'] = s.desc
      
      temp.push synapse
    end
    return temp
  end
  
  ## this one is for building our custom JSON autocomplete format for typeahead
  def autocomplete_synapse_array_json(synapses)
    temp = []
    synapses.each do |s|
      synapse = {}
      synapse['id'] = s.id
      synapse['label'] = s.desc
      synapse['value'] = s.desc
      synapse['permission'] = s.permission
      synapse['mapCount'] = s.maps.count
      synapse['originator'] = s.user.name
      synapse['rtype'] = "synapse"
      
      temp.push synapse
    end
    return temp
  end

end

app/views/synapses/_new.html.erb
<%#
  # @file
  # Partial for rendered a new synapse form
  # TODO: Is this used? Where?
  #%>
<div class="anypage">
	<%= form_for Synapse.new, url: synapses_url, remote: true do |form| %>
    <%= form.text_field :desc, :placeholder => "describe the connection..." %>
    <%= form.hidden_field :topic1id, :value => 0 %>
    <%= form.hidden_field :topic2id, :value => 0 %>
    <%= form.hidden_field :grabSynapse, :value => "null" %>
	<% end %>
</div>

app/views/synapses/create.js.erb
/*
 * @file
 * Javascript called when you create a new synapse.
 */
$('#new_synapse').fadeOut('fast');
$('#synapse_desc').typeahead('setQuery','');
$('#synapse_topic1id').attr('value','0');
$('#synapse_topic2id').attr('value','0');
$('#synapse_grabSynapse').attr('value','null');
// reset the draw synapse positions to false
MetamapsModel.synapseStartCoord = false;
MetamapsModel.synapseEndCoord = false;

var temp1, temp2, temp;	
		 
if ( Mconsole != null) {
    temp1 = Mconsole.graph.getNode(<%= @synapse.topic1.id %>);
    temp2 = Mconsole.graph.getNode(<%= @synapse.topic2.id %>);
    temp2.setData('dim', 25, 'current');
    Mconsole.graph.addAdjacence(temp1, temp2, {});
    temp = Mconsole.graph.getAdjacence(temp1.id, temp2.id);
    temp.setDataset('start', {  
      lineWidth: 0.4,
      alpha: 0.1      
      });
    temp.setDataset('end', {
      lineWidth: 2,
      alpha: 1
    });
    var d = new Array(<%= @synapse.node1_id.to_s() %>, <%= @synapse.node2_id.to_s() %>);
    temp.setDataset('current', {  
      desc: '<%= @synapse.desc %>',  
      showDesc: true, //will be changed by selectEdge
      category: '<%= @synapse.category %>',
      id: '<%= @synapse.id %>',
      userid: '<%= @synapse.user.id %>',
      username: '<%= @synapse.user.name %>',			
      permission: '<%= @synapse.permission %>'
      });
    temp.data.$direction = d;
    Mconsole.fx.animate({
      modes: ['edge-property:lineWidth:alpha'],
      duration: 100,
      onComplete: function() {
        setTimeout(function (){
          temp.setData('showDesc', false);
          Mconsole.plot();
        }, 3000);
      } 
    });
}
else {
  json = <%= @synapse.selfplusnodes_as_json.html_safe %>
  initialize("chaotic");
}

app/views/synapses/destroy.js.erb
/*
 * @file
 * Javascript called when you destroy a node
 */

app/views/synapses/removefrommap.js.erb
/* 
 * @file
 * Javascript executed when a synapse is removed from a map
 * TODO: Is this file even used?
 */

app/views/synapses/update.js.erb
/*
 * @file
 * Javascript called when you update a synapse
 */