config/routes.rb
ISSAD::Application.routes.draw do

  root to: 'main#home', via: :get
  
  match 'faq', to: 'main#faq', via: :get, as: :faq
  
  # for mobile
   match 'newtopic', to: 'main#newtopic', via: :get, as: :newtopic
  # end for mobile 
   
  
  match '/search/topics', to: 'main#searchtopics', via: :get, as: :searchtopics
  match '/search/maps', to: 'main#searchmaps', via: :get, as: :searchmaps
  match '/search/mappers', to: 'main#searchmappers', via: :get, as: :searchmappers
  match '/search/synapses', to: 'main#searchsynapses', via: :get, as: :searchsynapses
  
  match 'maps/:id/savelayout', to: 'maps#savelayout', via: :put, as: :savelayout
  match 'topics/:map_id/:topic_id/removefrommap', to: 'topics#removefrommap', via: :post, as: :removefrommap
  match 'synapses/:map_id/:synapse_id/removefrommap', to: 'synapses#removefrommap', via: :post, as: :removefrommap
  
  resources :topics, except: [:index, :new, :edit] do
    get :autocomplete_topic, :on => :collection
  end
  match 'topics/:id/:format', to: 'topics#json', via: :get, as: :json
  
  resources :synapses, except: [:index, :new, :edit, :show]
  match 'synapses/:id/:format', to: 'synapses#json', via: :get, as: :json
  
  match 'maps/active', to: 'maps#index', via: :get, as: :activemaps
  match 'maps/new', to: 'maps#index', via: :get, as: :newmaps
  match 'maps/mappers/:id', to: 'maps#index', via: :get, as: :usermaps
  match 'maps/topics/:id', to: 'maps#index', via: :get, as: :topicmaps
  
  
  resources :maps, except: [:new, :edit]
  match 'maps/:id/embed', to: 'maps#embed', via: :get, as: :embed
  match 'maps/:id/:format', to: 'maps#json', via: :get, as: :json
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  
  resources :users, except: :show

  resources :mappings
  
end

app/views/layouts/_account.html.erb
<%#
  # @file
  # The inner HTML of the account box that comes up in the bottom left
  #%>

<% if authenticated? %>
  <% account = current_user %>
  <h3 class="accountHeader">Hello <%= account.name.split[0...1][0] %>!</h3>
  <ul>
    <li class="accountIcon accountMaps"><a href="/maps/mappers/<%= account.id %>">My Maps</a></li>
    <li class="accountIcon accountSettings"><%= link_to "Settings", edit_user_url(account) %></li>
    <li class="accountIcon accountInvite openLightbox" data-open="invite"><span>Share Invite</span></li>
    <li class="accountIcon accountLogout"><%= link_to "Logout", "/sign_out", id: "Logout" %></li>
  </ul>
<% else %>
  <h3 class="accountHeader">Sign In</h3>
  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { class: "loginAnywhere" }) do |f| %>
        <div>
          <%= f.label :email %>
          <%= f.email_field :email, :autofocus => true %>
        </div>
        <div>
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <% if devise_mapping.rememberable? -%>
        <div><%= f.check_box :remember_me %> <%= f.label :remember_me %><div class="clearfloat"></div></div>
        <% end -%>
        <div>
          <%= f.submit "Sign in" %><br>
          
        </div>
  <% end %>
  <div class="links">
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %>
    <% end -%>
  </div>
<% end %>

app/views/layouts/_cheatsheet.html.erb
<%#
  # @file
  # The inner HTML of the cheatsheet
  #%>

<h3>Quick Reference Guide</h3>
        
<div class="cheatsheetColumn cOne">
  <h4>Topics</h4>
    <div class="csItem"><span class="csTitle">Add New Topic:</span> Double-click on canvas</div>
    <div class="csItem"><span class="csTitle">Select Metacode:</span> Scroll on spinner, or Tab / Shift+Tab</div>
    <div class="csItem"><span class="csTitle">Creating New Topic:</span> Hit Enter after typing topic name</div>
    <div class="csItem"><span class="csTitle">Get Existing Topic:</span> Click on (or use Up/Down->Enter) to pick from auto-suggestions</div>
    <div class="csItem"><span class="csTitle">Open Topic Card:</span> Double-click on topic icon</div>
    <div class="csItem"><span class="csTitle">Edit Topic Type:</span> Click on metacode in open topic card</div>
    <div class="csItem"><span class="csTitle">Open Topic View:</span> Click on 'leave page' icon in topic card (opens in new tab)</div>
  <h4>Navigation</h4>
    <div class="csItem"><span class="csTitle">Move (Pan) Across Canvas:</span> Click on canvas and drag</div>
    <div class="csItem"><span class="csTitle">Zoom In/Out</span> Scroll mouse on canvas</div>
    <div class="csItem"><span class="csTitle">Back to Center:</span> Refresh page</div>
</div>


<div class="cheatsheetColumn cTwo">
  <h4>Synapses</h4>
    <div class="csItem"><span class="csTitle">Create Synapse:</span> Right-click/Alt+Click on topic and drag to other topic, enter synapse name or choose suggested</div>
    <div class="csItem"><span class="csTitle">Create Topic with Synapse:</span> Right-click/Alt+Click on topic and drag to empty part of canvas</div>
    <div class="csItem"><span class="csTitle">View Synapse Description:</span> Hover over synapse</div>
    <div class="csItem"><span class="csTitle">Open Synapse Card:</span> Double-click synapse</div>
    <div class="csItem"><span class="csTitle">Edit Synapse Description:</span> Click synapse description in synapse card</div>
    <div class="csItem"><span class="csTitle">Change Synapse Direction:</span> Check/Uncheck directional arrow boxes</div>
  <h4>Selection</h4>
    <div class="csItem"><span class="csTitle">Select Topic or Synapse:</span> Click on one</div>
    <div class="csItem"><span class="csTitle">Select Multiple:</span> Shift+Click on canvas and drag around topics, or use Shift+Click to add/remove individually</div>
    <div class="csItem"><span class="csTitle">Move Multiple:</span> Select desired, Click and drag on a selected topic</div>
    <div class="csItem"><span class="csTitle">Hide/Remove/Delete:</span> Right-click/Alt+Click on selection</div>
    <div class="csItem"><span class="csTitle">Deselect All:</span> Hit Esc, or click any topic</div>
</div>

<div class="clearfloat"></div>

app/views/layouts/_lightboxes.html.erb
<%#
  # @file
  # 
  #%>


<div id="lightbox_overlay">
  <div id="lightbox_main">
    <a id="lightbox_close" onclick="cancelMapCreate('fork_map');cancelMapCreate('new_map');return false;" href="#"></a>
    <div id="lightbox_content">
      
      <div class="lightboxContent" id="about">
        <h3>About IdeaWall</h3>
        
        <p>IdeaWall is a prototype web platform created for REAP within the FELT lab. It is a customized instance of the technology that powers Metamaps.cc, a free and open source web platform for changemakers, innovators, educators and students. The technology is evolving for a range of applications amidst a growing network of designers, developers, practitioners, entrepreneurs, and artists.</p>
        <p>The IdeaWall platform enables realtime collaborative ideation and sensemaking - helping connect people, ideas and systems with rich detail, in order to weave those relationships into actionable insights and stories. IdeaWall and Metamaps.cc are toolkits that help individuals and communities build and visualize their shared knowledge to unlock their collective intelligence. </p>
        
        <ul>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="http://metamaps.cc" target="_blank">check out Metamaps.cc</a></li>
        </ul>
        <div class="clearfloat"></div>
      </div>
      
      <div class="lightboxContent" id="tutorial">
        <h3>Tutorial</h3>
        <div>Coming soon...</div>
        <!--<iframe width="510" height="383" src="//www.youtube.com/embed/0Bd8XxlNG3U?rel=0" frameborder="0" allowfullscreen></iframe>-->
      </div>
      
      <div class="lightboxContent" id="cheatsheet">
        <%= render :partial => 'layouts/cheatsheet' %>
      </div>
      
      <% if authenticated? %>
        <div class="lightboxContent" id="invite">
          <h3>Send Invites</h3>
          <p>You can invite others to the IdeaWall platform. Send them this link</p>
          <p class="green">http://reap.herokuapp.com/users/sign_up</p>
          <p>and give them the access code shown below.</p>
          <% mapper = current_user %>
          <p class="green"><%= mapper.code %></p>
        </div>
      
        <% # this is the create new map form %>
        <div class="lightboxContent" id="newmap">  
          <%= render :partial => 'maps/new' %>
        </div>
      
        <% if (controller_name == "maps" || controller_name == "topics" ) && action_name == "show"  %>
        <div class="lightboxContent" id="forkmap">  
          <%= render :partial => 'maps/fork' %>
        </div>
        <% end %>
      <% end %>
      
    </div>
  </div>
  <div id="lightbox_screen" onclick="cancelMapCreate('fork_map');cancelMapCreate('new_map');return false;" style="height: 100%;"></div>
</div>

app/views/layouts/_searchtemplates.html.erb
<%#
  # @file
  # templates for the upper right autocomplete results
  #%>

<div class="templates">

<div class="topicTemplate">
<div class="result{{rtype}}">
  <div class="topicMetacode">
    <img src="{{typeImageURL}}" class="topicIcon" />
    <span class="metacodeTip">{{type}}</span>
  </div>
  <div class="resultText">
    <p class="resultTitle">{{label}}</p>
    <p class="resultDesc">{{description}}</p>
  </div>
  <div class="autoOptions">
    
    <% if controller_name == 'maps' && action_name == 'show' && authenticated? && @map.authorize_to_edit(@current) %>
    <button class="addToMap hoverForTip" onclick="return keepFromCommons(event, {{id}})">
      <span class="tip">add to map</span>
    </button>
    <% end %>
    <a href="/topics/{{id}}" target="_blank" class="goTo hoverForTip">
      <span class="tip">open in new tab</span>
    </a>
    <div class="mapCount hoverForTip">
      <span class="tip">appears on this # of maps</span>
      {{mapCount}}
    </div>
    <div class="synapseCount hoverForTip">
      <span class="tip"> has this # of synapses</span>
      {{synapseCount}}
    </div>
    <div class="topicOriginatorIcon hoverForTip">
      <span class="tip topicOriginator">created by {{originator}}</span>
    </div>
    <div class="topicPermission {{permission}} hoverForTip">
      <span class="tip">topic is {{permission}}</span>
    </div>
  </div>
  <div class="clearfloat"></div>
</div>
</div>

<div class="mapTemplate">
<div class="result{{rtype}}">
  <img class="icon" src="/assets/map.png">
  <div class="resultText">
    <p class="resultTitle">{{label}}</p>
    <p class="resultDesc">{{description}}</p>
  </div>
  <div class="autoOptions">
    <a href="/maps/{{id}}" target="_blank" class="goTo hoverForTip">
      <span class="tip">open in new tab</span>
    </a>
    <div class="topicCount hoverForTip">
      <span class="tip">has this # of topics</span>
      {{topicCount}}
    </div>
    <div class="synapseCount hoverForTip">
      <span class="tip">has this # of synapses</span>
      {{synapseCount}}
    </div>
    <div class="mapContributorsIcon hoverForTip">
      <span class="tip mapContributors">{{contributorList}}</span>
      {{contributorCount}}
    </div>
    <div class="mapPermission {{permission}} hoverForTip">
      <span class="tip">map is {{permission}}</span>
    </div>
  </div>
  <div class="clearfloat"></div>
</div>
</div>

<div class="mapperTemplate">
<div class="result{{rtype}}">
  <img class="icon" width="28" height="28" src="/assets/MMCCicon_mapper.png">
  <div class="resultText">
    <p class="resultTitle">{{label}}</p>
  </div>
  <div class="autoOptions">
    <a href="/maps/mappers/{{id}}" target="_blank" class="goTo hoverForTip">
      <span class="tip">open in new tab</span>
    </a>
    <div class="mapCount hoverForTip">
      <span class="tip">created this # of maps</span>
      {{mapCount}}
    </div>
  </div>
  <div class="clearfloat"></div>
</div>
</div>

<div class="synapseTemplate">
  <div class="result{{rtype}}">
  <p class="autocompleteSection synapseDesc">{{label}}</p>
  <div class="autocompleteSection synapsePermission {{permission}}"></div>
  <div class="autocompleteSection synapseOriginatorIcon hoverForTip">
    <span class="tip synapseOriginator">{{originator}}</span>
  </div>
  <div class="clearfloat"></div>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<%#
  # @file
  # Main application file. Holds scaffolding present on every page.
  # Then a certain non-partial view (no _ preceding filename) will be
  # displayed within, based on URL
  #%>

<!DOCTYPE html>
<html>
<head>
  <title><%=h yield(:title) %></title>
  <% if authenticated? %>
    <script type="text/javascript">
      var userid = <%= user.id %>;
      var username = "<%= user.name %>";
    </script>
  <% else %>
    <script type="text/javascript">
      var userid = null;
      var username = null;
    </script>  
  <% end %>
  <script>
    var imgArray = new Object();
    
    <% Metacode.all.each do |m| %>
      imgArray['<%= m.name %>'] = new Image(); imgArray['<%= m.name %>'].src = '/assets/<%= m.icon %>';
    <% end %>
  </script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="//use.typekit.net/tki2nyo.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <script type="text/javascript" src="//use.typekit.net/obp7wss.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body class="<%= (action_name == "show") ? "mapBody" : "" %>" >

  <% if notice %>
  <p class="notice metamaps"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert metamaps"><%= alert %></p>
  <% end %>
       
  <%= content_tag :div, class: authenticated? ? "main authenticated" : "main unauthenticated" do %>

    <div class="wrapper" id="wrapper">
      <div class="sidebarSearch">
        <div class="sidebarSearchIcon"></div>
        <input type="text" class="sidebarSearchField"></input>
        <div class="clearfloat"></div>
        <%= render :partial => 'layouts/searchtemplates' %>
      </div>
      <div class="sidebarAccount">
        <div class="sidebarAccountIcon"></div>
        <div class="sidebarAccountBox <%= authenticated? ? 'loggedin' : 'loggedout' %>">
          <%= render :partial => 'layouts/account' %>
        </div>
      </div>
			<%= yield %>
		</div>
		
		<div class="footer">
      <div class="logo">
          <ul class="menu">
                <li class="beta" onclick="BAROMETER.show();">
                    FEEDBACK!
                </li>
                <li class="meta openLightbox" data-open="about">ABOUT</li>
                <li class="tutorial openLightbox" data-open="tutorial">TUTORIAL</li>
                <li class="exploreMaps"><%= link_to "EXPLORE MAPS", activemaps_url %></li>
          </ul>
          <div id="mainTitle"><%= link_to "IdeaWall", root_url %></div>
      </div>
      <% if authenticated? %>
        <div class="addMap openLightbox" data-open="newmap"></div>
      <% end %>
    </div>
    
  <% end %>
  
    <style type='text/css'>@import url('http://getbarometer.s3.amazonaws.com/assets/barometer/css/barometer.css');</style>
    <script src='http://getbarometer.s3.amazonaws.com/assets/barometer/javascripts/barometer.js' type='text/javascript'></script>
    <script type="text/javascript" charset="utf-8">
      BAROMETER.load('Scqak8nyHdFEkezKMNeQp');
    </script>
  <%= render :partial => 'layouts/lightboxes' %>
</body>
</html>

app/views/layouts/application.mobile.erb
<%#
  # @file
  # Main application file. Holds scaffolding present on every page.
  # Then a certain non-partial view (no _ preceding filename) will be
  # displayed within, based on URL
  #%>

<!DOCTYPE html>
<html>
<head>
  <title><%=h yield(:title) + "" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript">
    var mapid = false;
  <% if authenticated? %>
    var userid = <%= user.id %>;
    var username = "<%= user.name %>";
  <% else %>
    var userid = null,username = null;
  <% end %>
  </script>
  <%= stylesheet_link_tag    "application.mobile", :media => "all" %>
  <%= javascript_include_tag "application.mobile" %>
  <script type="text/javascript" src="//use.typekit.net/obp7wss.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    
  <%= csrf_meta_tags %>
</head>
<body>

     <% if action_name == "newtopic" %>
       <%= yield %>
     <% else %>
     <div data-role="page" >
 
        <div data-role="header" data-theme="c">
            <h1><%=h yield(:title) %></h1>
        </div><!-- /header -->
 
        <div data-role="content">
            <%= yield %>
        </div><!-- /content -->
 
        <div data-role="footer" data-position="fixed" data-theme="c">
            <% if authenticated? %>
            <div data-role="navbar" class="nav-veqtor">  
              <ul>  
                <li><a href="/maps/mappers/<%= user.id %>" onclick="mapid = false;" data-icon="Map">My Maps</a></li>
                <li><a href="/newtopic" id="createNewEntity" onclick="pickMap()" data-icon="Add" data-transition="slideup" data-prefetch="true">New Topic</a></li>
                <li><a href="/sign_out" data-icon="Lock">Logout</a></li>
              </ul>  
            </div>
            <% else %>
            <h4>IdeaWall</h4>
            <% end %>
        </div><!-- /footer -->
 
    </div><!-- /page -->
    <% end %>
    
<% if authenticated? %>
<script>

function pickMap() {
  if (mapid) {
    $("#addToMaps option[value='" + mapid + "']").attr("selected", "selected");
    $("#addToMaps").selectmenu("refresh");
  }
}

$('#new-entity').live('pagecreate',function(){

    var addToMaps = []; 
     
    // create Topic
    function createTopic(name, metacode, description) {
      return $.ajax({
          type: "POST",
          url: "/topics",
          dataType: "json",
          data: { "topic": { "name": name, "desc": description, "metacode": metacode, "x": 0, "y":0, "grabTopic": "null" } },
          success: (function (data, textStatus, jqXHR) {
              // reset the form and change the button back to say "Submit"
              $('#new-entity form')[0].reset();
              $('#new-entity').find('.addIt .ui-btn-text').text("Created!");
              setTimeout(function(){
                $('#new-entity').find('.addIt .ui-btn-text').text("Create!");
                
                var prev = $.mobile.urlHistory.getPrev();
                
                if (prev != undefined) {
                  if (prev.url.indexOf('maps') != -1 && prev.url.indexOf('maps/mappers') == -1 ) {  
                    $.mobile.changePage(prev.url, { transition: 'slidedown' });
                  } else {
                    $.mobile.changePage( '/topics/' + data.id, { transition: 'slidedown' });
                  }
                } else {
                  $.mobile.changePage( '/maps/mappers/' + userid.toString(), { transition: 'slidedown' });
                }
              }, 1000);
              
              for (var i = 0; i < addToMaps.length; i++) {
                createMapping( data.id, parseInt(addToMaps[i]) );
              }
          })
      });
    } 
    
    // create Mapping
    function createMapping(topicid, mapid) {
      return $.ajax({
          type: "POST",
          url: "/mappings",
          dataType: "json",
          data: { "xloc": 0, "yloc": 0, "topic": { "id": topicid }, "map": { "id": mapid }  },
          success: (function (data, textStatus, jqXHR) {

          })
      });
    }
    
    // add events to the back and submit buttons
    // this is the back button
    $('#new-entity').find('.backToList').click(function(evt){
      evt.preventDefault();
      evt.stopPropagation();
      $('#new-entity form')[0].reset();
      if ($.mobile.urlHistory.getPrev() != undefined) {
        $.mobile.changePage($.mobile.urlHistory.getPrev().url, { transition: 'slidedown' });
      } else {
        $.mobile.changePage( '/maps/mappers/' + userid.toString(), { transition: 'slidedown' });
      }
    });

    // add the events for the submit button
    $('#new-entity').find('.addIt').click(function(evt){
        console.log(evt);
        evt.preventDefault();
        evt.stopPropagation();
        
        if ($('#title').val() == "" || $('#type option:selected').length == 0) {
          alert('Please enter a title and select a type');
          return;
        }
        // change the button to a loading image
        $('#new-entity').find('.addIt .ui-btn-text').html('<img src="/assets/loading.gif" />');
        
        $('#addToMaps option:selected').each(function() {
          addToMaps.push( $(this).val() );
        });
        
        // addit!
        createTopic( $('#title').val() , $('#type option:selected').val() , $('#description').val() )
    }); // end $('.addIt').click
});
</script>
<% end %>

</body>
</html>